# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5aaa20900c9ab35403b3c29d7dfe187151005979b7aa6c0c767fdbc03ce0aa798260dec8f2c120cdbbab28dffcc36c7be55ec4d2d492738f860dc580e77edc

test:
  secret_key_base: 5f6953cceef76758118ad5c0416faf8e3c342cc1f605ae409aa0e88ad3bfbb45dc99f42c7e1b01194542687383cdca8f6c20eee7e58dff1e68e83327f45e2e9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
